import type { Release, Character } from './types';

export const releases: Release[] = [
    {
        id: '207',
        title: 'Last Drift',
        type: 'album',
        releaseDate: '2025-09-04',
        coverArt: '/albums/LAST DRIFT.jpg',
        description: "",
        streamingLinks: [
            { platform: 'Spotify', url: 'https://open.spotify.com/album/3NZe4vDiROZ3GGFM4m6pLR?si=KupnAGjqTOq_NgFgALAHNA' },
            { platform: 'Apple Music', url: 'https://music.apple.com/album/example' },
            { platform: 'Bandcamp', url: 'https://miigii.bandcamp.com/album/midnight-dreams' },
            { platform: 'YouTube Music', url: 'https://music.youtube.com/playlist?list=example' },
        ],
        characterIds: ['char1', 'char2'],
    }, {
        id: '206',
        title: 'Mia and the Pre Drops',
        type: 'album',
        releaseDate: '2024-05-01',
        coverArt: '/albums/Mia and the Pre Drops.jpg',
        description: "",
        streamingLinks: [
            { platform: 'Spotify', url: 'https://open.spotify.com/album/3NZe4vDiROZ3GGFM4m6pLR?si=KupnAGjqTOq_NgFgALAHNA7' },
        ],
    },
    {
        id: '205',
        title: 'Light of Love',
        type: 'album',
        releaseDate: '2024-01-10',
        coverArt: '/albums/Light of Love.jpg',
        description: "",
        streamingLinks: [
            { platform: 'Spotify', url: 'https://open.spotify.com/album/3NZe4vDiROZ3GGFM4m6pLR?si=KupnAGjqTOq_NgFgALAHNA9' },
        ],
    },
    {
        id: '204',
        title: 'Miigii',
        type: 'album',
        releaseDate: '2022-01-10',
        coverArt: '/albums/Miigii.jpg',
        description: "",
        streamingLinks: [
            { platform: 'Spotify', url: 'https://open.spotify.com/album/3NZe4vDiROZ3GGFM4m6pLR?si=KupnAGjqTOq_NgFgALAHNA9' },
        ],
    },
    {
        id: '203',
        title: 'Peppi and the Pre Drops',
        type: 'album',
        releaseDate: '2024-01-10',
        coverArt: '/albums/Peppi and the Pre Drops.jpg',
        description: "",
        streamingLinks: [
            { platform: 'Spotify', url: 'https://open.spotify.com/album/3NZe4vDiROZ3GGFM4m6pLR?si=KupnAGjqTOq_NgFgALAHNA9' },
        ],
    },
    {
        id: '202',
        title: '2020',
        type: 'album',
        releaseDate: '2020-12-18',
        coverArt: '/albums/2020.jpg',
        description: "",
        streamingLinks: [
            { platform: 'Spotify', url: 'https://open.spotify.com/album/3NZe4vDiROZ3GGFM4m6pLR?si=KupnAGjqTOq_NgFgALAHNA9' },
        ],
    },
    {
        id: '201',
        title: 'Visions',
        type: 'album',
        releaseDate: '2019-11-20',
        coverArt: '/albums/Visions.jpg',
        description: "",
        streamingLinks: [
            { platform: 'Spotify', url: 'spotify.com0' },
        ],
    },
    {
        id: '056',
        title: 'Torille',
        type: 'single',
        releaseDate: '2025-01-20',
        coverArt: '/albums/Torille.jpg',
        description: "",
        streamingLinks: [
            { platform: 'Spotify', url: 'https://open.spotify.com/artist/4r0TLwVYXZ15k1H4TQ6zA5' },
        ],
    },
    {
        id: '055',
        title: 'Pilluralli',
        type: 'single',
        releaseDate: '2024-12-15',
        coverArt: '/albums/Pilluralli.jpg',
        description: "",
        streamingLinks: [
            { platform: 'Spotify', url: 'https://open.spotify.com/album/3NZe4vDiROZ3GGFM4m6pLR?si=KupnAGjqTOq_NgFgALAHNA0' },
        ],
    },
    {
        id: '054',
        title: 'Running',
        type: 'single',
        releaseDate: '2024-11-02',
        coverArt: '/albums/Running.jpg',
        description: "",
        streamingLinks: [
            { platform: 'Spotify', url: 'https://open.spotify.com/album/3NZe4vDiROZ3GGFM4m6pLR?si=KupnAGjqTOq_NgFgALAHNA1' },
        ],
    },
    {
        id: '053',
        title: 'Cattack',
        type: 'single',
        releaseDate: '2024-08-05',
        coverArt: '/albums/Cattack.jpg',
        description: "",
        streamingLinks: [
            { platform: 'Spotify', url: 'https://newsroom.spotify.com/2025-12-03/wrapped-top-artists-songs-albums-podcasts-audiobooks/' },
        ],
    },
    {
        id: '052',
        title: 'Bailao',
        type: 'single',
        releaseDate: '2024-09-10',
        coverArt: '/albums/Bailao.jpg',
        description: "",
        streamingLinks: [
            { platform: 'Spotify', url: 'https://open.spotify.com/album/3NZe4vDiROZ3GGFM4m6pLR?si=KupnAGjqTOq_NgFgALAHNA2' },
        ],
    },
    {
        id: '051',
        title: 'Mantra da Deriva',
        type: 'single',
        releaseDate: '2024-07-22',
        coverArt: '/albums/Mantra da Deriva.jpg',
        description: "",
        streamingLinks: [
            { platform: 'Spotify', url: 'spotify.com2' },
        ],
    },
    {
        id: '050',
        title: 'FORTE',
        type: 'single',
        releaseDate: '2024-06-18',
        coverArt: '/albums/FORTE.jpg',
        description: "",
        streamingLinks: [
            { platform: 'Spotify', url: 'spotify.com3' },
        ],
    },
    {
        id: '049',
        title: 'BASTU EM FÚRIA',
        type: 'single',
        releaseDate: '2024-05-12',
        coverArt: '/albums/Bastu.jpg',
        description: "",
        streamingLinks: [
            { platform: 'Spotify', url: 'spotify.com4' },
        ],
    },
    {
        id: '048',
        title: 'HALO',
        type: 'single',
        releaseDate: '2025-01-10',
        coverArt: '/albums/Halo.jpg',
        description: "",
        streamingLinks: [
            { platform: 'Spotify', url: 'https://open.spotify.com/artist/0F45rLCHw8eT6oW8uX0W8V/discography/all' },
        ],
    },
    {
        id: '047',
        title: 'Don\'t Stop',
        type: 'single',
        releaseDate: '2024-10-25',
        coverArt: '/albums/Don\'t Stop.jpg',
        description: "",
        streamingLinks: [
            { platform: 'Spotify', url: 'spotify.com0' },
        ],
    },
    {
        id: '046',
        title: 'Marathon of Betrayal',
        type: 'single',
        releaseDate: '2024-10-10',
        coverArt: '/albums/Marathon of Betrayal.jpg',
        description: "",
        streamingLinks: [
            { platform: 'Spotify', url: 'spotify.com1' },
        ],
    },
    {
        id: '045',
        title: 'Hit the Breaks',
        type: 'single',
        releaseDate: '2024-07-28',
        coverArt: '/albums/Hit the Breaks.jpg',
        description: "",
        streamingLinks: [
            { platform: 'Spotify', url: 'https://open.spotify.com/album/3NZe4vDiROZ3GGFM4m6pLR?si=KupnAGjqTOq_NgFgALAHNA3' },
        ],
    },
    {
        id: '044',
        title: 'Favela',
        type: 'single',
        releaseDate: '2024-06-01',
        coverArt: '/albums/Favela.jpg',
        description: "",
        streamingLinks: [
            { platform: 'Spotify', url: 'https://open.spotify.com/album/3NZe4vDiROZ3GGFM4m6pLR?si=KupnAGjqTOq_NgFgALAHNA4' },
        ],
    },
    {
        id: '043',
        title: 'PONTO CEGO',
        type: 'single',
        releaseDate: '2024-05-01',
        coverArt: '/albums/Ponto Cego.jpg',
        description: "",
        streamingLinks: [
            { platform: 'Spotify', url: 'https://open.spotify.com/album/3NZe4vDiROZ3GGFM4m6pLR?si=KupnAGjqTOq_NgFgALAHNA5' },
        ],
    },
    {
        id: '042',
        title: 'Transformation',
        type: 'single',
        releaseDate: '2024-02-14',
        coverArt: '/albums/Transformation.jpg',
        description: "",
        streamingLinks: [
            { platform: 'Spotify', url: 'spotify.com6' },
        ],
    },
    {
        id: '041',
        title: 'honk',
        type: 'single',
        releaseDate: '2024-01-20',
        coverArt: '/albums/honk.jpg',
        description: "",
        streamingLinks: [
            { platform: 'Spotify', url: 'spotify.com7' },
        ],
    },
    {
        id: '040',
        title: 'Peppi and the Pre Drops, Vol. 2',
        type: 'single',
        releaseDate: '2024-03-20',
        coverArt: '/albums/Peppi and the Pre Drops, Vol. 2.jpg',
        description: "",
        streamingLinks: [
            { platform: 'Spotify', url: 'https://open.spotify.com/album/3NZe4vDiROZ3GGFM4m6pLR?si=KupnAGjqTOq_NgFgALAHNA8' },
        ],
    },
    {
        id: '039',
        title: 'TRAFFIC',
        type: 'single',
        releaseDate: '2023-11-10',
        coverArt: '/albums/Traffic.jpg',
        description: "",
        streamingLinks: [
            { platform: 'Spotify', url: 'spotify.com9' },
        ],
    },
    {
        id: '038',
        title: 'Lo-fi Dreams',
        type: 'single',
        releaseDate: '2021-09-03',
        coverArt: '/albums/Lo-fi Dreams.jpg',
        description: "",
        streamingLinks: [
            { platform: 'Spotify', url: 'https://open.spotify.com/artist/4r0TLwVYXZ15k1H4TQ6zA5/discography/all' },
        ],
    },
    {
        id: '137',
        title: 'SOS',
        type: 'ep',
        releaseDate: '2021-04-16',
        coverArt: '/albums/SOS.jpg',
        description: "",
        streamingLinks: [
            { platform: 'Spotify', url: 'https://artists.spotify.com/get-started' },
        ],
    },
    {
        id: '036',
        title: 'Podcast Junkie',
        type: 'single',
        releaseDate: '2020-03-27',
        coverArt: '/albums/Podcast Junkie.jpg',
        description: "",
        streamingLinks: [
            { platform: 'Spotify', url: 'https://support.spotify.com/us/artists/article/creating-an-artist-profile-on-spotify/' },
        ],
    },
    {
        id: '035',
        title: 'The Sound',
        type: 'single',
        releaseDate: '2019-11-08',
        coverArt: '/albums/The Sound.jpg',
        description: "",
        streamingLinks: [
            { platform: 'Spotify', url: 'https://artists.spotify.com/blog/making-the-most-of-your-artist-profile-on-spotify' },
        ],
    },
    {
        id: '034',
        title: 'Destruction',
        type: 'single',
        releaseDate: '2019-09-27',
        coverArt: '/albums/Destruction.jpg',
        description: "",
        streamingLinks: [
            { platform: 'Spotify', url: 'https://open.spotify.com/album/3NZe4vDiROZ3GGFM4m6pLR?si=KupnAGjqTOq_NgFgALAHNA16' },
        ],
    },
    {
        id: '033',
        title: 'Soul',
        type: 'single',
        releaseDate: '2019-07-26',
        coverArt: '/albums/Soul.jpg',
        description: "",
        streamingLinks: [
            { platform: 'Spotify', url: 'https://open.spotify.com/album/3NZe4vDiROZ3GGFM4m6pLR?si=KupnAGjqTOq_NgFgALAHNA17' },
        ],
    },
    {
        id: '032',
        title: 'It Blows Me Away',
        type: 'single',
        releaseDate: '2019-06-21',
        coverArt: '/albums/It Blows me Away.jpg',
        description: "",
        streamingLinks: [
            { platform: 'Spotify', url: 'https://open.spotify.com/album/3NZe4vDiROZ3GGFM4m6pLR?si=KupnAGjqTOq_NgFgALAHNA18' },
        ],
    },
    {
        id: '031',
        title: 'The Legend of the Onyx Stranger',
        type: 'single',
        releaseDate: '2019-05-17',
        coverArt: '/albums/The Legend of the Onyx Stranger.jpg',
        description: "",
        streamingLinks: [
            { platform: 'Spotify', url: 'https://open.spotify.com/album/3NZe4vDiROZ3GGFM4m6pLR?si=KupnAGjqTOq_NgFgALAHNA19' },
        ],
    },
    {
        id: '030',
        title: 'Distant',
        type: 'single',
        releaseDate: '2019-04-12',
        coverArt: '/albums/Distant.jpg',
        description: "",
        streamingLinks: [
            { platform: 'Spotify', url: 'https://open.spotify.com/album/3NZe4vDiROZ3GGFM4m6pLR?si=KupnAGjqTOq_NgFgALAHNA20' },
        ],
    },
    {
        id: '029',
        title: 'Careless',
        type: 'single',
        releaseDate: '2019-03-08',
        coverArt: '/albums/Careless.jpg',
        description: "",
        streamingLinks: [
            { platform: 'Spotify', url: 'https://open.spotify.com/album/3NZe4vDiROZ3GGFM4m6pLR?si=KupnAGjqTOq_NgFgALAHNA21' },
        ],
    },
    {
        id: '028',
        title: 'I Don\'t Know',
        type: 'single',
        releaseDate: '2019-01-25',
        coverArt: '/albums/I Dont Know.jpg',
        description: "",
        streamingLinks: [
            { platform: 'Spotify', url: 'https://open.spotify.com/album/3NZe4vDiROZ3GGFM4m6pLR?si=KupnAGjqTOq_NgFgALAHNA22' },
        ],
    },
    {
        id: '027',
        title: 'Big Room | Bigger Presents',
        type: 'single',
        releaseDate: '2018-12-14',
        coverArt: '/albums/Big Room Bigger Presents.jpg',
        description: "",
        streamingLinks: [
            { platform: 'Spotify', url: 'https://open.spotify.com/album/3NZe4vDiROZ3GGFM4m6pLR?si=KupnAGjqTOq_NgFgALAHNA23' },
        ],
    },
    {
        id: '026',
        title: 'Metronome',
        type: 'single',
        releaseDate: '2018-11-23',
        coverArt: '/albums/Metronome.jpg',
        description: "",
        streamingLinks: [
            { platform: 'Spotify', url: 'https://open.spotify.com/album/3NZe4vDiROZ3GGFM4m6pLR?si=KupnAGjqTOq_NgFgALAHNA24' },
        ],
    },
    {
        id: '025',
        title: 'Pretender',
        type: 'single',
        releaseDate: '2018-11-02',
        coverArt: '/albums/Pretender.jpg',
        description: "",
        streamingLinks: [
            { platform: 'Spotify', url: 'https://open.spotify.com/album/3NZe4vDiROZ3GGFM4m6pLR?si=KupnAGjqTOq_NgFgALAHNA25' },
        ],
    },
    {
        id: '024',
        title: 'Suburban Satisfaction',
        type: 'single',
        releaseDate: '2018-10-12',
        coverArt: '/albums/Suburban Satisfaction.jpg',
        description: "",
        streamingLinks: [
            { platform: 'Spotify', url: 'https://open.spotify.com/album/3NZe4vDiROZ3GGFM4m6pLR?si=KupnAGjqTOq_NgFgALAHNA26' },
        ],
    },
    {
        id: '023',
        title: 'Set Me Free',
        type: 'single',
        releaseDate: '2018-09-21',
        coverArt: '/albums/Set Me Free.jpg',
        description: "",
        streamingLinks: [
            { platform: 'Spotify', url: 'https://open.spotify.com/album/3NZe4vDiROZ3GGFM4m6pLR?si=KupnAGjqTOq_NgFgALAHNA27' },
        ],
    },
    {
        id: '022',
        title: 'Asd',
        type: 'single',
        releaseDate: '2018-08-31',
        coverArt: '/albums/asd.jpg',
        description: "",
        streamingLinks: [
            { platform: 'Spotify', url: 'https://open.spotify.com/album/3NZe4vDiROZ3GGFM4m6pLR?si=KupnAGjqTOq_NgFgALAHNA28' },
        ],
    },
    {
        id: '021',
        title: 'Waiting',
        type: 'single',
        releaseDate: '2018-08-10',
        coverArt: '/albums/Waiting.jpg',
        description: "",
        streamingLinks: [
            { platform: 'Spotify', url: 'https://open.spotify.com/album/3NZe4vDiROZ3GGFM4m6pLR?si=KupnAGjqTOq_NgFgALAHNA29' },
        ],
    },
    {
        id: '020',
        title: 'She',
        type: 'single',
        releaseDate: '2018-07-20',
        coverArt: '/albums/She.jpg',
        description: "",
        streamingLinks: [
            { platform: 'Spotify', url: 'https://newsroom.spotify.com/2025-12-03/wrapped-top-artists-songs-albums-podcasts-audiobooks/0' },
        ],
    },
    {
        id: '019',
        title: 'Game On',
        type: 'single',
        releaseDate: '2018-06-29',
        coverArt: '/albums/Game On.jpg',
        description: "",
        streamingLinks: [
            { platform: 'Spotify', url: 'https://newsroom.spotify.com/2025-12-03/wrapped-top-artists-songs-albums-podcasts-audiobooks/1' },
        ],
    },
    {
        id: '018',
        title: 'Jungle Demon',
        type: 'single',
        releaseDate: '2018-06-08',
        coverArt: '/albums/Jungle Demon.jpg',
        description: "",
        streamingLinks: [
            { platform: 'Spotify', url: 'https://newsroom.spotify.com/2025-12-03/wrapped-top-artists-songs-albums-podcasts-audiobooks/2' },
        ],
    },
    {
        id: '017',
        title: 'Style of the Future',
        type: 'single',
        releaseDate: '2018-05-18',
        coverArt: '/albums/Style of the Future.jpg',
        description: "",
        streamingLinks: [
            { platform: 'Spotify', url: 'https://newsroom.spotify.com/2025-12-03/wrapped-top-artists-songs-albums-podcasts-audiobooks/3' },
        ],
    },
    {
        id: '016',
        title: 'Cruising',
        type: 'single',
        releaseDate: '2018-04-27',
        coverArt: '/albums/Cruising.jpg',
        description: "",
        streamingLinks: [
            { platform: 'Spotify', url: 'https://newsroom.spotify.com/2025-12-03/wrapped-top-artists-songs-albums-podcasts-audiobooks/4' },
        ],
    },
    {
        id: '015',
        title: 'Swing',
        type: 'single',
        releaseDate: '2018-04-06',
        coverArt: '/albums/Swing.jpg',
        description: "",
        streamingLinks: [
            { platform: 'Spotify', url: 'https://newsroom.spotify.com/2025-12-03/wrapped-top-artists-songs-albums-podcasts-audiobooks/5' },
        ],
    },
    {
        id: '014',
        title: 'You\'ll Never Know',
        type: 'single',
        releaseDate: '2018-03-16',
        coverArt: '/albums/Youll Never Know.jpg',
        description: "",
        streamingLinks: [
            { platform: 'Spotify', url: 'https://newsroom.spotify.com/2025-12-03/wrapped-top-artists-songs-albums-podcasts-audiobooks/6' },
        ],
    },
    {
        id: '013',
        title: 'Beat Is the Answer VIP',
        type: 'single',
        releaseDate: '2018-02-23',
        coverArt: '/albums/Beat is the Answer VIP.jpg',
        description: "",
        streamingLinks: [
            { platform: 'Spotify', url: 'https://newsroom.spotify.com/2025-12-03/wrapped-top-artists-songs-albums-podcasts-audiobooks/7' },
        ],
    },
    {
        id: '012',
        title: 'Learning Machine',
        type: 'single',
        releaseDate: '2018-02-02',
        coverArt: '/albums/Learning Machine.jpg',
        description: "",
        streamingLinks: [
            { platform: 'Spotify', url: 'https://newsroom.spotify.com/2025-12-03/wrapped-top-artists-songs-albums-podcasts-audiobooks/8' },
        ],
    },
    {
        id: '011',
        title: 'Cordion',
        type: 'single',
        releaseDate: '2018-01-12',
        coverArt: '/albums/Cordion.jpg',
        description: "",
        streamingLinks: [
            { platform: 'Spotify', url: 'https://newsroom.spotify.com/2025-12-03/wrapped-top-artists-songs-albums-podcasts-audiobooks/9' },
        ],
    },
    {
        id: '010',
        title: 'B U',
        type: 'single',
        releaseDate: '2018-01-05',
        coverArt: '/albums/BU.jpg',
        description: "",
        streamingLinks: [
            { platform: 'Spotify', url: 'https://open.spotify.com/artist/0F45rLCHw8eT6oW8uX0W8V/discography/all0' },
        ],
    },
    {
        id: '009',
        title: 'Loose Battle',
        type: 'single',
        releaseDate: '2017-12-08',
        coverArt: '/albums/Loose Battle.jpg',
        description: "",
        streamingLinks: [
            { platform: 'Spotify', url: 'https://open.spotify.com/artist/0F45rLCHw8eT6oW8uX0W8V/discography/all1' },
        ],
    },
    {
        id: '008',
        title: 'Yellow Yellow',
        type: 'single',
        releaseDate: '2017-11-17',
        coverArt: '/albums/Yellow Yellow.jpg',
        description: "",
        streamingLinks: [
            { platform: 'Spotify', url: 'https://open.spotify.com/artist/0F45rLCHw8eT6oW8uX0W8V/discography/all2' },
        ],
    },
    {
        id: '007',
        title: 'Silent Riot',
        type: 'single',
        releaseDate: '2017-10-27',
        coverArt: '/albums/Silent Riot.jpg',
        description: "",
        streamingLinks: [
            { platform: 'Spotify', url: 'https://open.spotify.com/artist/0F45rLCHw8eT6oW8uX0W8V/discography/all3' },
        ],
    },
    {
        id: '006',
        title: 'Escape from Reality',
        type: 'single',
        releaseDate: '2017-10-06',
        coverArt: '/albums/Escape from Reality.jpg',
        description: "",
        streamingLinks: [
            { platform: 'Spotify', url: 'https://open.spotify.com/artist/0F45rLCHw8eT6oW8uX0W8V/discography/all4' },
        ],
    },
    {
        id: '005',
        title: 'Beat Is the Answer',
        type: 'single',
        releaseDate: '2017-09-15',
        coverArt: '/albums/Beat is the Answer.jpg',
        description: "",
        streamingLinks: [
            { platform: 'Spotify', url: 'https://open.spotify.com/artist/0F45rLCHw8eT6oW8uX0W8V/discography/all5' },
        ],
    },
    {
        id: '004',
        title: 'Forgotten Bubbles',
        type: 'single',
        releaseDate: '2017-08-25',
        coverArt: '/albums/Forgotten Bubbles.jpg',
        description: "",
        streamingLinks: [
            { platform: 'Spotify', url: 'https://open.spotify.com/artist/0F45rLCHw8eT6oW8uX0W8V/discography/all6' },
        ],
    },
    {
        id: '003',
        title: 'Regret Knows How to Party',
        type: 'single',
        releaseDate: '2017-08-04',
        coverArt: '/albums/Regret Knows How to Party.jpg',
        description: "",
        streamingLinks: [
            { platform: 'Spotify', url: 'https://open.spotify.com/artist/0F45rLCHw8eT6oW8uX0W8V/discography/all7' },
        ],
    },
    {
        id: '002',
        title: 'Real Weekend',
        type: 'single',
        releaseDate: '2017-07-14',
        coverArt: '/albums/Real Weekend.jpg',
        description: "",
        streamingLinks: [
            { platform: 'Spotify', url: 'https://open.spotify.com/artist/0F45rLCHw8eT6oW8uX0W8V/discography/all8' },
        ],
    },
    {
        id: '001',
        title: 'Creativity on Ice',
        type: 'single',
        releaseDate: '2017-06-23',
        coverArt: '/albums/Creativity on Ice.jpg',
        description: "",
        streamingLinks: [
            { platform: 'Spotify', url: 'https://open.spotify.com/artist/0F45rLCHw8eT6oW8uX0W8V/discography/all9' },
        ],
    },
    {
        id: '-001',
        title: 'Cry of Sand',
        type: 'single',
        releaseDate: '2017-06-23',
        coverArt: '/albums/Cry of Sand.jpg',
        description: "",
        streamingLinks: [
            { platform: 'Spotify', url: 'https://open.spotify.com/artist/0F45rLCHw8eT6oW8uX0W8V/discography/all9' },
        ],
    },
    {
        id: '-002',
        title: 'Illusion',
        type: 'single',
        releaseDate: '2017-06-23',
        coverArt: '/albums/Illusion.jpg',
        description: "",
        streamingLinks: [
            { platform: 'Spotify', url: 'https://open.spotify.com/artist/0F45rLCHw8eT6oW8uX0W8V/discography/all9' },
        ],
    },
    {
        id: '-003',
        title: 'Looking for the Muse',
        type: 'single',
        releaseDate: '2017-06-23',
        coverArt: '/albums/Looking for the Muse.jpg',
        description: "",
        streamingLinks: [
            { platform: 'Spotify', url: 'https://open.spotify.com/artist/0F45rLCHw8eT6oW8uX0W8V/discography/all9' },
        ],
    }
];

export const characters: Character[] = [
    {
        id: '0char1',
        name: 'Mia',
        description: 'Mia, a character who embodies a sleek, "modern-cool" aesthetic with a bit of a futuristic edge. Mia’s style is streamlined, mixing streetwear comfort with sharp, intentional details.',
        image: '/characters/main/Mia.jpg',
    },
    {
        id: '0char2',
        name: 'Peppi',
        description: 'Peppi likely has a personality as sharp as her fashion sense. She’s the type of character who is effortlessly cool but possesses a quirky, confident charm—never afraid to mix textures, colors, and eras to create a look that is uniquely her own.',
        image: '/characters/main/Peppi.jpg',
    },
    {
        id: '0char3',
        name: 'Aki',
        description: 'Aki possesses a quiet, contemplative confidence and likely values quality and longevity in his choices. While the others might jump into the latest digital trends, Aki is the one analyzing the situation, offering a steady hand and a discerning eye.',
        image: '/characters/main/Aki.jpg',
    },
];

